# Generated by Django 5.2.14 on 2026-05-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume_text', models.TextField()),
                ('job_description', models.TextField()),
                ('score', models.IntegerField()),
                ('matched_skills', models.JSONField()),
                ('missing_skills', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
